version: '3'
services:

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sv_backend
      MYSQL_ROOT_PASSWORD: "testpassword"
      MYSQL_PASSWORD: "testpassword"
      MYSQL_USER: "horecarobot"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network
  java:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "
      ./wait_for_it.sh db:3306 &&
      java -jar backend.jar"
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - db
#Docker Networks
networks:
  app-network:
    driver: bridge