name: CI

on:
  push:
    branches:
      - '*'

jobs:
  Unit_Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get upgrade -y && sudo apt install maven -y

      - name: Setup Docker
        run: docker compose up --build -d

      - name: Unit Tests
        run: docker compose exec -e SPRING_PROFILES_ACTIVE='docker' bartender-backend mvn test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        run: |
          export DOCKER_BUILDKIT=0
          export COMPOSE_DOCKER_CLI_BUILD=0
          docker build -t iqfx/horeca-backend:backend .
          docker push iqfx/horeca-backend:backend
